### ISSUE TITLE
change Import styling for the global-form-control-status

### ISSUE THREAD

**Issue by Arigatouz** [PacktPublishing/Effective-Angular#35]
Hello Roberto
I was following up on the concept of adding style as a library and making a "@global-in-dev dependency " 
it was amazing I love it
but I found an issue 
when we go to the ==> libs/finance/ui/expenses-registration-forms/src/lib/add-expense/add-expense.component.scss

and we find this import 
import '@global/styling/form-control-status';
this will actually through an error it will say :
![image](https://github.com/user-attachments/assets/389523f2-e1c0-4ec8-bb32-3d7e662d2eb5)

I think to avoid this 
we need to import it like this 
"import '@global/styling/form-control-status.scss';
we need to add the extension of the file in case someone stumbles on it

**Comment by RHeckers** [comment]
Hi Ali,

You should be able to import it without the .scss extension. 

When you check the node_modules, do you find the .scss file here:
node_modules\@global\styling\form-control-status.scss

If not, you need to install the package again because it didn't successfully install it in that case. 

When I clone my repo and comment in and out the import:
@import '@global/styling/form-control-status';

I do see the styling being applied (or not when I comment it out). 

So you can also clone my repo to compare. Otherwise maybe remove the package and reinstall it. 

If that doesn't help I need some additional information because I can't reproduce it on my end,
